apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: tomcat
  name: tomcat
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: tomcat
    spec:
      hostNetwork: true
      containers:
      image: tomcatimage
      ports:
      - containerPort: 80
      resources: {}
      VolumeMounts:
      - mountPath: /usr/local/tomcat/logs/
        name: tomcat-claim0
    volumes:
      - name: tomcat-claim0
status: {}